### ISSUE TITLE
'python2_download_facescrub.py' crashes in between the download for actors

### ISSUE THREAD

**Issue by dyno8426** [lightalchemist/FaceScrub#1]
I ran the script to download FaceScrub dataset along with the cropped-up faces of actors as follows:

$ python python2_download_facescrub.py facescrub_actors.txt actors/ --crop_face --logfile=actors.log --timeout=30

It crashes in between while downloading some file related to "Steve Carell" giving the following error:

... [rest of the terminal output] ...
Downloading http://www.moviecitizens.com/wp-content/uploads/2012/06/Steve-Carell-Brick-Tamland-MC.png
Traceback (most recent call last):
  File "python2_download_facescrub.py", line 308, in <module>
    main()
  File "python2_download_facescrub.py", line 298, in main
    response = download_image(counter, url, sha256, args.timeout)
  File "python2_download_facescrub.py", line 144, in download_image
    response = requests.get(url, headers=headers, timeout=timeout)
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 605, in send
    r.content
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 303, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 450, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/adarshc/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 420, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/home/adarshc/anaconda/lib/python2.7/httplib.py", line 705, in _safe_read
    raise IncompleteRead(''.join(s), amt)
httplib.IncompleteRead: IncompleteRead(5162 bytes read, 2934 more expected)

Can someone please help me resolve this?
Thanks in advance.

**Comment by lightalchemist** [comment]
@adarshc I was not able to replicate the problem on my Ubuntu setup but that could just be due to differences in our configuration.

I added extra code for starting (and ending) the download at a specific line in the file, as well as catching generic Exception. With this change, I'm able to download from the line you specified till the end of the actors.txt file.

Can you try downloading from the problem line again and see if it still cause the script to crash? I believe it should now catch the exception and skip it.

**Comment by dyno8426** [comment]
@lightalchemist , thank you so much for your quick updates. It resolved the problem and successfully caught the exception to bypass downloading from the link where it was failing initially.
Plus, thanks also for adding that simple but necessary feature of resuming the download after the point where it last failed.
